server:
  port: 8080
  context-path: /ai-stock-decision
spring:
  application:
    name: ai-stock-decision
#feign客户端配置
feign:
  hystrix:
    #设置feign开启hystrix(服务保护）
    enabled: true

#ribbon配置
ribbon:
  #ribbon的超时时间要大于hystrix的超时时间，否则 hystrix自定义的超时时间毫无意义
  ReadTimeout: 5000
  ConnectTimeout: 5000

#hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #feign整合hystrix 光设置Hystrix 超时没用的要配合ribbon超时
            timeoutInMilliseconds: 3000
      circuitBreaker:
        #默认20 ，熔断的阈值，如何服务报错满足3次，熔断器就会打开，就算之后请求正确的数据也不行。
        requestVolumeThreshold: 3
        #默认5S ， 等5S之后熔断器会处于半开状态，然后下一次请求的正确和错误讲决定熔断器是否真的关闭和是否继续打开
        sleepWindowInMilliseconds: 8000
